config/routes.rb
Rails.application.routes.draw do
  resources :manga_lists
  root 'manga_lists#index'

end

app/models/manga_list.rb
class MangaList < ActiveRecord::Base
  mount_uploader :avatar, MangaUploader

  u = User.new
  u.avatar = params[:file] # Assign a file like this, or

  # like this
  File.open('somewhere') do |f|
    u.avatar = f
  end

  u.save!
  u.avatar.url # => '/url/to/file.png'
  u.avatar.current_path # => 'path/to/file.png'
  u.avatar_identifier # => 'file.png'
end

# u.avatar will never return nil, even if there is no photo associated to it. To check if a photo was saved to the model, use u.avatar.file.nil? instead.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/manga_lists_controller.rb
class MangaListsController < ApplicationController
  before_action :set_manga_list, only: [:show, :edit, :update, :destroy]
  params.require(:user).permit(:email, :first_name, :last_name, {avatars: []})
  

  # GET /manga_lists
  # GET /manga_lists.json
  def index
    @manga_lists = MangaList.all
  end

  # GET /manga_lists/1
  # GET /manga_lists/1.json
  def show
  end

  # GET /manga_lists/new
  def new
    @manga_list = MangaList.new
    
  end

  # GET /manga_lists/1/edit
  def edit
  end

  # POST /manga_lists
  # POST /manga_lists.json
  def create
    @manga_list = MangaList.new(manga_list_params)

    respond_to do |format|
      if @manga_list.save
        format.html { redirect_to @manga_list, notice: 'Manga list was successfully created.' }
        format.json { render :show, status: :created, location: @manga_list }
      else
        format.html { render :new }
        format.json { render json: @manga_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manga_lists/1
  # PATCH/PUT /manga_lists/1.json
  def update
    respond_to do |format|
      if @manga_list.update(manga_list_params)
        format.html { redirect_to @manga_list, notice: 'Manga list was successfully updated.' }
        format.json { render :show, status: :ok, location: @manga_list }
      else
        format.html { render :edit }
        format.json { render json: @manga_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manga_lists/1
  # DELETE /manga_lists/1.json
  def destroy
    @manga_list.destroy
    respond_to do |format|
      format.html { redirect_to manga_lists_url, notice: 'Manga list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manga_list
      @manga_list = MangaList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manga_list_params
      params.require(:manga_list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manga_lists_helper.rb
module MangaListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/manga_lists/_form.html.erb
<%= form_for(@manga_list) do |f| %>

<%= form.file_field :avatars, multiple: true %>


  <% if @manga_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manga_list.errors.count, "error") %> prohibited this manga_list from being saved:</h2>

      <ul>
      <% @manga_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manga_lists/edit.html.erb
<h1>Editing Manga List</h1>

<%= render 'form' %>

<%= link_to 'Show', @manga_list %> |
<%= link_to 'Back', manga_lists_path %>

app/views/manga_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manga Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manga_lists.each do |manga_list| %>
      <tr>
        <td><%= link_to manga_list.name, manga_list %></td>
<!--         <td><%= link_to 'Edit', edit_manga_list_path(manga_list) %></td>
        <td><%= link_to 'Destroy', manga_list, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manga list', new_manga_list_path %>

app/views/manga_lists/new.html.erb
<h1>New Manga List</h1>

<%= render 'form' %>

<%= link_to 'Back', manga_lists_path %>

app/views/manga_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manga_list.name %>
</p>

<%= button_to "Add chapter", action: "new" %>
<form method="post" action="/controller/new" class="button_to" %>
</form>

<%= link_to 'Edit', edit_manga_list_path(@manga_list) %> |
<%= link_to 'Back', manga_lists_path %>